In [1]:
# Importy
import pandas as pd
import numpy as np

# Wczytanie danych

In [46]:
# Wczytanie danych
df = pd.read_csv("sleep_health_dataset.csv")

# Kształt zbioru i spradzenie danych
print(f"Kształt zbioru: {df.shape}\n")
df.head()

Kształt zbioru: (100000, 32)

,person_id,age,gender,occupation,bmi,country,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,...,heart_rate_resting_bpm,sleep_aid_used,shift_work,room_temperature_celsius,weekend_sleep_diff_hrs,season,day_type,cognitive_performance_score,sleep_disorder_risk,felt_rested
0,1,29,Female,Driver,25.7,Japan,6.19,6.6,22.5,19.3,...,63,0,0,20.1,1.84,Autumn,Weekday,73.4,Healthy,0
1,2,55,Female,Software Engineer,22.0,USA,8.32,6.9,26.9,14.9,...,52,1,0,18.0,0.13,Winter,Weekend,99.4,Healthy,1
2,3,42,Male,Nurse,25.0,India,3.74,1.0,20.2,16.2,...,72,0,1,17.9,1.67,Spring,Weekend,2.5,Severe,0
3,4,37,Female,Student,29.5,India,6.79,6.4,17.7,17.7,...,71,0,0,19.1,2.37,Summer,Weekend,67.8,Healthy,0
4,5,23,Male,Lawyer,23.6,Spain,5.02,3.2,23.3,18.3,...,71,0,0,19.7,1.26,Summer,Weekday,38.1,Mild,0

In [10]:
# Statystyki kolumn: typy, wartości niepuste, ilość danych
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   gender                       100000 non-null  str
 3   occupation                   100000 non-null  str
 4   bmi                          100000 non-null  float64
 5   country                      100000 non-null  str
 6   sleep_duration_hrs           100000 non-null  float64
 7   sleep_quality_score          100000 non-null  float64
 8   rem_percentage               100000 non-null  float64
 9   deep_sleep_percentage        100000 non-null  float64
 10  sleep_latency_mins           100000 non-null  int64
 11  wake_episodes_per_night      100000 non-null  int64
 12  caffeine_mg_before_bed       100000 non-null  int64
 13  alcohol_units_before_bed     100000 non-null  float64
 14  screen_time_before_bed_mins  100000 non-null  int64
 15  exercise_day                 100000 non-null  int64
 16  steps_that_day               100000 non-null  int64
 17  nap_duration_mins            100000 non-null  int64
 18  stress_score                 100000 non-null  float64
 19  work_hours_that_day          100000 non-null  float64
 20  chronotype                   100000 non-null  str
 21  mental_health_condition      100000 non-null  str
 22  heart_rate_resting_bpm       100000 non-null  int64
 23  sleep_aid_used               100000 non-null  int64
 24  shift_work                   100000 non-null  int64
 25  room_temperature_celsius     100000 non-null  float64
 26  weekend_sleep_diff_hrs       100000 non-null  float64
 27  season                       100000 non-null  str
 28  day_type                     100000 non-null  str
 29  cognitive_performance_score  100000 non-null  float64
 30  sleep_disorder_risk          100000 non-null  str
 31  felt_rested                  100000 non-null  int64
dtypes: float64(11), int64(13), str(8)
memory usage: 29.3 MB

In [12]:
# Statystyki kolumn liczbowych
df.describe()

,person_id,age,bmi,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,sleep_latency_mins,wake_episodes_per_night,caffeine_mg_before_bed,...,nap_duration_mins,stress_score,work_hours_that_day,heart_rate_resting_bpm,sleep_aid_used,shift_work,room_temperature_celsius,weekend_sleep_diff_hrs,cognitive_performance_score,felt_rested
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,34.706870,26.289673,6.423986,4.871144,20.243968,20.253375,19.836810,3.346610,38.849500,...,14.936840,5.733285,7.134059,66.57017,0.561610,0.084420,20.538093,1.200634,59.227295,0.390120
std,28867.657797,11.036373,4.479578,1.274627,1.506517,3.411354,4.251096,7.584343,1.920877,69.395818,...,21.387567,1.619194,3.482878,7.22821,0.496192,0.278018,2.897565,0.786667,22.249665,0.487779
min,1.000000,18.000000,16.000000,3.000000,1.000000,10.000000,5.000000,1.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,45.00000,0.000000,0.000000,15.000000,-1.000000,0.000000,0.000000
25%,25000.750000,26.000000,23.200000,5.530000,3.800000,18.000000,17.400000,14.000000,2.000000,0.000000,...,0.000000,4.800000,4.700000,62.00000,0.000000,0.000000,18.500000,0.670000,44.200000,0.000000
50%,50000.500000,33.000000,26.300000,6.360000,4.900000,20.300000,20.300000,19.000000,3.000000,0.000000,...,0.000000,5.800000,7.400000,67.00000,1.000000,0.000000,20.500000,1.200000,60.400000,0.000000
75%,75000.250000,42.000000,29.300000,7.270000,6.000000,22.600000,23.200000,25.000000,5.000000,80.000000,...,30.000000,6.800000,9.700000,71.00000,1.000000,0.000000,22.500000,1.740000,75.800000,1.000000
max,100000.000000,69.000000,45.000000,10.500000,10.000000,30.000000,30.000000,58.000000,8.000000,400.000000,...,116.000000,10.000000,18.000000,99.00000,1.000000,1.000000,28.000000,3.000000,100.000000,1.000000

In [29]:
# Przegląd kolumn kategorycznych
kolumny_kategoryczne = df.select_dtypes(include="str").columns

for kol in kolumny_kategoryczne:
    print(f"\n-- {kol} ({df[kol].nunique()} unikalnych) --")
    print(df[kol].value_counts())
    print("-" * 32)
    print(f"Suma liczności: {df[kol].value_counts().sum()}")

-- gender (3 unikalnych) --
gender
Female    50203
Male      47823
Other      1974
Name: count, dtype: int64
--------------------------------
Suma liczności: 100000

-- occupation (12 unikalnych) --
occupation
Student              14851
Software Engineer    12068
Nurse                10073
Manager               8101
Teacher               8047
Doctor                7868
Retired               7036
Sales                 7017
Freelancer            7016
Driver                6996
Homemaker             5923
Lawyer                5004
Name: count, dtype: int64
--------------------------------
Suma liczności: 100000

-- country (15 unikalnych) --
country
USA            20050
India          17840
Japan           8089
UK              8024
Brazil          7146
Germany         6026
Canada          4995
France          4982
Australia       4948
Italy           4018
South Korea     3971
Mexico          3888
Netherlands     3040
Spain           2011
Sweden           972
Name: count, dtype: int64
--------------------------------
Suma liczności: 100000

-- chronotype (3 unikalnych) --
chronotype
Neutral    45396
Evening    29643
Morning    24961
Name: count, dtype: int64
--------------------------------
Suma liczności: 100000

-- mental_health_condition (4 unikalnych) --
mental_health_condition
Healthy       69993
Anxiety       15134
Depression     9854
Both           5019
Name: count, dtype: int64
--------------------------------
Suma liczności: 100000

-- season (4 unikalnych) --
season
Summer    25121
Spring    25110
Autumn    24892
Winter    24877
Name: count, dtype: int64
--------------------------------
Suma liczności: 100000

-- day_type (2 unikalnych) --
day_type
Weekday    71428
Weekend    28572
Name: count, dtype: int64
--------------------------------
Suma liczności: 100000

-- sleep_disorder_risk (4 unikalnych) --
sleep_disorder_risk
Healthy     54156
Mild        33479
Moderate     8299
Severe       4066
Name: count, dtype: int64
--------------------------------
Suma liczności: 100000

**Wnioski po wczytaniu danych i wstępnej analizie:**
- Zbiór posiada 100000 wierszy i 32 kolumny.
- Zbiór nie zawiera brakujących wartości - wszytkie kolumny mają po 100000 rekordów.
- Zbiór pochodzi ze strony Kaggle i wygląda na dobrze przygotowany do analizy.
- Zakresy liczbowe wyglądają realnie (np. wiek:  18-69, BMI: 16-45, temperatura 15-28).
- Kategorie tekstowe są czyste i ujednolicone - wszytkie zaczynają się od dużych liter i bez literówek.

*Dlatego główną częścią przygotowania danych będą konwersje typów i utworzenie kolumn pochodnych, a nie usuwanie braków.*

# Czyszczenie i przygotowanie danych

## Obsługa braków

Zbiór nie zawiera brakujących wartości (potwierdzone wcześniej: `isnull().sum()` = 0),więc obsługa braków nie jest tu potrzebna. Poniżej pokazuję jednak, jak podszedłbym do tego problemu, gdyby braki wystąpiły. Cała demonstracja działa na kopii danych (`df_demo`) i nie wpływa na główny zbiór, który jest kompletny.

In [53]:
# Utworzenie kopi zbioru
df_demo = df.copy()

# Wstawienie braków w kilku kolumnach.
df_demo.loc[df_demo.sample(frac=0.05, random_state=42).index, "bmi"] = np.nan
df_demo.loc[df_demo.sample(frac=0.03, random_state=1).index, "stress_score"] = np.nan
df_demo.loc[df_demo.sample(frac=0.02, random_state=2).index, "occupation"] = np.nan

# Wyświetlenie braków
print("Braki w zbiorze dodatkowym:")
print(df_demo[["bmi", "stress_score", "occupation"]].isnull().sum())

Braki w zbiorze dodatkowym:
bmi             5000
stress_score    3000
occupation      2000
dtype: int64

In [54]:
# Kolumny liczbowe - wypełnienie mediany
df_demo["bmi"] = df_demo["bmi"].fillna(df_demo["bmi"].median())
df_demo["stress_score"] = df_demo["stress_score"].fillna(df_demo["stress_score"].median())

# Kolumna kategoryczna - wyoełnienie modą
df_demo["occupation"] = df_demo["occupation"].fillna(df_demo["occupation"].mode()[0])

# Wyświetlenie braków
print("Braki po wypełnieniu:")
print(df_demo[["bmi", "stress_score", "occupation"]].isnull().sum())

Braki po wypełnieniu:
bmi             0
stress_score    0
occupation      0
dtype: int64

In [56]:
# Utworzenie kopi zbioru
df_demo2 = df.copy()

# Wstawienie braków w bmi
df_demo2.loc[df_demo2.sample(frac=0.05, random_state=42).index, "bmi"] = np.nan

print("Przed usunięciem:", df_demo2.shape)

# Usuwa wiersze, w których brakuje wartości w kolumnie bmi
df_demo2 = df_demo2.dropna(subset=["bmi"])

print("Po usunięciu:  ", df_demo2.shape)
print("Usunięto wierszy:", 100000 - len(df_demo2))

Przed usunięciem: (100000, 32)
Po usunięciu:   (95000, 32)
Usunięto wierszy: 5000

W zbiorze nie występują braki, dlatego powyższą obsługę przeprowadziłem na kopii danych (`df_demo`) z celowo wstawionymi wartościami `NaN` — wyłącznie po to, żeby pokazać technikę. Główny zbiór pozostaje kompletny.

Braki najpierw sprawdzam (`isnull().sum()`), a dopiero potem decyduję, co z nimi zrobić. Wybór strategii zależy od skali problemu: przy niewielkiej liczbie braków (poniżej ~5%) można usunąć wiersze (`dropna`), natomiast gdy braków jest dużo, lepiej je wypełnić (`fillna`), żeby nie tracić danych.
Kolumny liczbowe wypełniam medianą — jest odporna na wartości odstające i sprawdza się lepiej niż średnia — a kolumny kategoryczne modą, czyli najczęstszą wartością. Jeśli braki obejmują ponad połowę kolumny, warto rozważyć usunięcie jej w całości.

## Konwersje typów

In [57]:
# Konwersja kolumn logicznych z wartościami 0/1 na wartości Tak/Nie i zmiana na typ category.
kolumny_binarne = ["exercise_day", "sleep_aid_used", "shift_work", "felt_rested"]

for kol in kolumny_binarne:
    if pd.api.types.is_numeric_dtype(df[kol]):
        df[kol] = df[kol].map({0: "Nie", 1: "Tak"}).astype("category")

# Sprawdzenie
df[kolumny_binarne].head()

  exercise_day sleep_aid_used shift_work felt_rested
0          Nie            Nie        Nie         Nie
1          Tak            Tak        Nie         Tak
2          Tak            Nie        Tak         Nie
3          Tak            Nie        Nie         Nie
4          Nie            Nie        Nie         Nie

In [58]:
# Zamiana kolumn tekstowych na typ category - oszczędność pamięci.
kolumny_kategoryczne = ["gender", "occupation", "country", "chronotype", "mental_health_condition", "season", "day_type", "sleep_disorder_risk"]

for kol in kolumny_kategoryczne:
    df[kol] = df[kol].astype("category")

# Sprawdzenie - niższe zużycie pamięci
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   gender                       100000 non-null  category
 3   occupation                   100000 non-null  category
 4   bmi                          100000 non-null  float64
 5   country                      100000 non-null  category
 6   sleep_duration_hrs           100000 non-null  float64
 7   sleep_quality_score          100000 non-null  float64
 8   rem_percentage               100000 non-null  float64
 9   deep_sleep_percentage        100000 non-null  float64
 10  sleep_latency_mins           100000 non-null  int64
 11  wake_episodes_per_night      100000 non-null  int64
 12  caffeine_mg_before_bed       100000 non-null  int64
 13  alcohol_units_before_bed     100000 non-null  float64
 14  screen_time_before_bed_mins  100000 non-null  int64
 15  exercise_day                 100000 non-null  category
 16  steps_that_day               100000 non-null  int64
 17  nap_duration_mins            100000 non-null  int64
 18  stress_score                 100000 non-null  float64
 19  work_hours_that_day          100000 non-null  float64
 20  chronotype                   100000 non-null  category
 21  mental_health_condition      100000 non-null  category
 22  heart_rate_resting_bpm       100000 non-null  int64
 23  sleep_aid_used               100000 non-null  category
 24  shift_work                   100000 non-null  category
 25  room_temperature_celsius     100000 non-null  float64
 26  weekend_sleep_diff_hrs       100000 non-null  float64
 27  season                       100000 non-null  category
 28  day_type                     100000 non-null  category
 29  cognitive_performance_score  100000 non-null  float64
 30  sleep_disorder_risk          100000 non-null  category
 31  felt_rested                  100000 non-null  category
dtypes: category(12), float64(11), int64(9)
memory usage: 16.4 MB

Kolumny logiczne (0/1) zamieniłem na czytelniejsze etykiety Tak/Nie, co ułatwi implementacje filtrów i legend na dashboardzie. Kolumny tekstowe o powtarzalnych wartościach przekonwertowałem na typ `category`, który pandas przechowuje jako liczby z mapą etykiet, co przy 100 000 wierszy realnie zmniejsza zużycie pamięci (z 29,3 MB do ok. 16,4 MB, czyli blisko 45%).